### ISSUE TITLE
원본코드

### ISSUE THREAD

**Issue by hoosiki** [riseryan89/fast-shop#1]
강의가 모두 공개 되었는데 레포지토리의 코드들이 완성형이 아닙니다.
강의 내용에서 사용되는 코드는 어디서 구할 수 있을까요?

**Comment by riseryan89** [comment]
BASE DIR 설정에 오류가 있었습니다. 올바르게 고쳐두었고 Requirements.txt 도 최신으로 프리즈 해두었습니다. 다시 pull 받으시면 보실 수 있을 겁니다. 추가적으로 기능추가 및 개선도 계속 할 예정이니 강의와 상관없이 종종 들려주세요!
